;Option C: Character Counter for Names
;
;Program:
;Create an LC-3 program that displays the frequency of characters of user full name.
;
;Input:
;User is prompt to input his or her full name.
;
;Output:
;Numerical value that represents the frequency of a character in the user fullname.

.ORIG x3000			;Starting address

	LEA R0, MSG		;LOAD MSG INTO R0
	PUTS			;PRINT R0

	LEA R1, NEG65   	;LOAD NEG65 INTO R1
	LDR R1, R1, #0  	;LOAD R1 INTO R1

INPUT		              	;INPUT PROCESS
  	IN                	;READ INPUT CHARACTER
  	ADD R4, R0, #-10  	;MINUS DECIMAL 10 BECAUSE THE ASCII EQUIVALENCE TO ENTER IS DECIMAL 10.
  	BRz OUTPUT        	;BRANCH TO OUTPUT IF ZERO 
				;IF ENTER IS PRESSED, CONTINUE TO OUTPUT

  	LEA R3, ARRAY     	;LOAD ARRAY INTO R3
  	ADD R0, R0, R1    	;SUBTRACT 65 FOR ASCII RELEVANCE
  	BRz CHARACTERCOUNTER   	;BRANCH TO CHARACTERCOUNTER IF ZERO

INPUTLOOP        		;ELSE RELEVENCE OF C/C++ TO READ THE INPUT
  	ADD R3, R3, #1  	;ADD TO THE NEXT INDEX IN THE ARRAY BY DECIMAL NUMBER
  	ADD R0, R0, #-1 	;SUBTRACT COUNTER BY DECIMAL 1
  	BRp INPUTLOOP   	;BRANCH BACK TO INPUTLOOP IF POSITIVE
				;THIS WILL LOOP THE INPUT PROCESS TO CONTINUE ASKING FOR A CHARACTER

CHARACTERCOUNTER       		;INITIATE THE COUNTER FOR THE CHARACTERS THAT WERE INPUT
  	LDR R0, R3, #0		;LOAD ARRAY INTO R0
  	ADD R0, R0, #1		;ADD VALUE OF ARRAY BY DECIMAL 1 TO COUNT THE CHARACTERS INPUTED
  	STR R0, R3, #0		;STORE NEW VALUE OF ARRAY
  	BR INPUT        	;UNCONDITIONAL BRANCH BACK TO INPUT
				;THIS COUNTS THE CHARACTERS INPUT

OUTPUT          		;OUTPUT PROCESS
  	LEA R2, POS58   	;LOAD POS58 INTO R2
  	LDR R2, R2, #0  	;LOAD R2 INTO R2
  	AND R0, R0, #0  	;CLEAR R0
				;THIS IS FOR THE ALPHABATICAL OUTPUT

  	LEA R5, POS65   	;LOAD POS65 INTO R5
  	LDR R5, R5, #0  	;LOAD R5 INTO R5
  	ADD R0, R5, #0  	;ADD R5 TO R0
				;THIS WILL PRINT OUT THE CHARACTERS

  	LEA R3, ARRAY   	;POINT BACK TO ARRAY
  	LEA R1, POS48   	;LOAD POS48 INTO R1
  	LDR R1, R1, #0  	;LOAD R1 INTO R1
				;THIS WILL PRINT OUT THE CHARACTER COUNTS

OUTPUTLOOP       		;OUTPUT RESULTS
  	OUT             	;PRINT OUTPUT

	LEA R0, DASH   		;LOAD DASH INTO R0
  	LDR R0, R0, #0  	;LOAD R0 INTO R0
  	OUT             	;PRINT OUT DASH INBETWEEN COUNTER

 	LDR R0, R3, #0  	;LOAD ARRAY INTO R0
  	ADD R3, R3, #1 		;ADD VALUE OF ARRAY BY DECIMAL 1
  	ADD R0, R0, R1  	;ASCII CONVERSION. DECIMAL 0 IS THE NEW DECIMAL 48
  	OUT             	;PRINT CHARACTER FREQUENCY

	LEA R0, SPACE   	;LOAD SPACE INTO R0
	LDR R0, R0, #0  	;LOAD R0 INTO R0
	OUT             	;PRINT OUT A SPACE INBETWEEN COUNTER

  	ADD R5, R5, #1  	;GO TO NEXT ASCII DECIMAL VALUE
  	ADD R0, R5, #0  	;ADD R5 TO R0 
  	ADD R2, R2, #-1 	;DECREASE LOOP COUNTER
  	BRp OUTPUTLOOP  	;BRANCH BACK TO OUTPUTLOOP IF POSITIVE 

HALT

MSG	.STRINGZ "ENTER YOUR FULL NAME ONE LETTER AT A TIME. PRESS ENTER WHEN DONE."
ARRAY  	.BLKW 26      		;ARRAY OF 26 INTEGERS.
NEG65  	.FILL #-65    		;CONSTANT FOR CONVERTING DECIMAL VALUE FROM ASCII (65 IS A)
POS58  	.FILL #58     		;CONSTANT FOR ALPHABET
DASH  	.FILL x002D   		;HEX VALUE IN ASCII
SPACE  	.FILL x0020 		;HEX VALUE IN ASCII
POS65	.FILL #65     		;CONSTANT FOR ASCII CAPITAL ALPHABET (A-Z)
POS48	.FILL #48     		;CONSTANT FOR ASCII DECIMAL (0-9)

	.END			;END THE PROGRAM